import { c as create_ssr_component } from "../../../chunks/ssr.js";
const css = {
  code: ".contact-content.svelte-16horv2{max-width:800px;margin:2rem auto;padding:0 1rem}.contact-info.svelte-16horv2{padding:2rem;background:var(--color-bg-1);border-radius:8px;text-align:center}.submit-button.svelte-16horv2{display:inline-block;padding:0.75rem 2rem;background-color:var(--color-theme-1);color:white;border:none;border-radius:4px;cursor:pointer;font-size:1rem;font-family:var(--font-body);text-decoration:none;transition:background-color 0.2s}.submit-button.svelte-16horv2:hover{background-color:#1a7ba1;color:white}@media(max-width: 768px){.contact-info.svelte-16horv2{padding:1.5rem}.submit-button.svelte-16horv2{text-align:center}}",
  map: '{"version":3,"file":"+page.svelte","sources":["+page.svelte"],"sourcesContent":["<svelte:head>\\n\\t<title>Contact - NIVED</title>\\n\\t<meta name=\\"description\\" content=\\"Get in touch with NIVED\\" />\\n</svelte:head>\\n\\n<div class=\\"container\\">\\n\\t<h1>Contact</h1>\\n\\t\\n\\t<div class=\\"contact-content\\">\\n\\t\\t<div class=\\"contact-info\\">\\n\\t\\t\\t<h2>Get in Touch</h2>\\n\\t\\t\\t<p>For booking inquiries and other business opportunities:</p>\\n\\n\\t\\t\\t<a href=\\"mailto:nickysaturnmusic@gmail.com\\" class=\\"submit-button\\">\\n\\t\\t\\t\\tSend Email\\n\\t\\t\\t</a>\\n\\t\\t</div>\\n\\t</div>\\n</div>\\n\\n<style>\\n\\t.contact-content {\\n\\t\\tmax-width: 800px;\\n\\t\\tmargin: 2rem auto;\\n\\t\\tpadding: 0 1rem;\\n\\t}\\n\\n\\t.contact-info {\\n\\t\\tpadding: 2rem;\\n\\t\\tbackground: var(--color-bg-1);\\n\\t\\tborder-radius: 8px;\\n\\t\\ttext-align: center;\\n\\t}\\n\\n\\t.contact-details {\\n\\t\\tmargin: 2rem 0;\\n\\t}\\n\\n\\t.contact-item {\\n\\t\\tdisplay: flex;\\n\\t\\talign-items: flex-start;\\n\\t\\tgap: 1rem;\\n\\t\\tmargin-bottom: 1.5rem;\\n\\t}\\n\\n\\t.contact-item i {\\n\\t\\tcolor: var(--color-theme-1);\\n\\t\\tfont-size: 1.2rem;\\n\\t\\tmargin-top: 0.2rem;\\n\\t}\\n\\n\\t.submit-button {\\n\\t\\tdisplay: inline-block;\\n\\t\\tpadding: 0.75rem 2rem;\\n\\t\\tbackground-color: var(--color-theme-1);\\n\\t\\tcolor: white;\\n\\t\\tborder: none;\\n\\t\\tborder-radius: 4px;\\n\\t\\tcursor: pointer;\\n\\t\\tfont-size: 1rem;\\n\\t\\tfont-family: var(--font-body);\\n\\t\\ttext-decoration: none;\\n\\t\\ttransition: background-color 0.2s;\\n\\t}\\n\\n\\t.submit-button:hover {\\n\\t\\tbackground-color: #1a7ba1;\\n\\t\\tcolor: white;\\n\\t}\\n\\n\\t@media (max-width: 768px) {\\n\\t\\t.contact-info {\\n\\t\\t\\tpadding: 1.5rem;\\n\\t\\t}\\n\\n\\t\\t.submit-button {\\n\\n\\t\\t\\ttext-align: center;\\n\\t\\t}\\n\\t}\\n</style>"],"names":[],"mappings":"AAqBC,+BAAiB,CAChB,SAAS,CAAE,KAAK,CAChB,MAAM,CAAE,IAAI,CAAC,IAAI,CACjB,OAAO,CAAE,CAAC,CAAC,IACZ,CAEA,4BAAc,CACb,OAAO,CAAE,IAAI,CACb,UAAU,CAAE,IAAI,YAAY,CAAC,CAC7B,aAAa,CAAE,GAAG,CAClB,UAAU,CAAE,MACb,CAmBA,6BAAe,CACd,OAAO,CAAE,YAAY,CACrB,OAAO,CAAE,OAAO,CAAC,IAAI,CACrB,gBAAgB,CAAE,IAAI,eAAe,CAAC,CACtC,KAAK,CAAE,KAAK,CACZ,MAAM,CAAE,IAAI,CACZ,aAAa,CAAE,GAAG,CAClB,MAAM,CAAE,OAAO,CACf,SAAS,CAAE,IAAI,CACf,WAAW,CAAE,IAAI,WAAW,CAAC,CAC7B,eAAe,CAAE,IAAI,CACrB,UAAU,CAAE,gBAAgB,CAAC,IAC9B,CAEA,6BAAc,MAAO,CACpB,gBAAgB,CAAE,OAAO,CACzB,KAAK,CAAE,KACR,CAEA,MAAO,YAAY,KAAK,CAAE,CACzB,4BAAc,CACb,OAAO,CAAE,MACV,CAEA,6BAAe,CAEd,UAAU,CAAE,MACb,CACD"}'
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-tle2se_START -->${$$result.title = `<title>Contact - NIVED</title>`, ""}<meta name="description" content="Get in touch with NIVED"><!-- HEAD_svelte-tle2se_END -->`, ""} <div class="container" data-svelte-h="svelte-7mku4r"><h1>Contact</h1> <div class="contact-content svelte-16horv2"><div class="contact-info svelte-16horv2"><h2>Get in Touch</h2> <p>For booking inquiries and other business opportunities:</p> <a href="mailto:nickysaturnmusic@gmail.com" class="submit-button svelte-16horv2">Send Email</a></div></div> </div>`;
});
export {
  Page as default
};
