import { c as create_ssr_component } from "../../../chunks/ssr.js";
const css = {
  code: ".tour-dates.svelte-134hhe.svelte-134hhe{max-width:800px;margin:2rem auto;padding:0 1rem}.tour-date.svelte-134hhe.svelte-134hhe{display:flex;align-items:center;padding:1.5rem;margin-bottom:1rem;background:var(--color-bg-1);border-radius:8px}.details.svelte-134hhe.svelte-134hhe{flex-grow:1}.details.svelte-134hhe h3.svelte-134hhe{margin:0}@media(max-width: 600px){.tour-date.svelte-134hhe.svelte-134hhe{flex-direction:column;text-align:center;gap:1rem;padding:1rem}}",
  map: '{"version":3,"file":"+page.svelte","sources":["+page.svelte"],"sourcesContent":["<svelte:head>\\n\\t<title>Tour - NIVED</title>\\n\\t<meta name=\\"description\\" content=\\"Check out upcoming tour dates and get tickets\\" />\\n</svelte:head>\\n\\n<div class=\\"container\\">\\n\\t<h1>Tour Dates</h1>\\n\\t\\n\\t<div class=\\"tour-dates\\">\\n\\t\\t<div class=\\"tour-date\\">\\n\\t\\t\\t<!-- <div class=\\"date\\">\\n\\t\\t\\t\\t<span class=\\"day\\">15</span>\\n\\t\\t\\t\\t<span class=\\"month\\">DEC</span>\\n\\t\\t\\t</div> -->\\n\\t\\t\\t<div class=\\"details\\">\\n\\t\\t\\t\\t<h3>Coming Soon</h3>\\n\\t\\t\\t</div>\\n\\t\\t\\t<!-- <a href=\\"#\\" class=\\"ticket-button\\">Get Tickets</a> -->\\n\\t\\t</div>\\n\\t</div>\\n</div>\\n\\n<style>\\n\\t.tour-dates {\\n\\t\\tmax-width: 800px;\\n\\t\\tmargin: 2rem auto;\\n\\t\\tpadding: 0 1rem;\\n\\t}\\n\\n\\t.tour-date {\\n\\t\\tdisplay: flex;\\n\\t\\talign-items: center;\\n\\t\\tpadding: 1.5rem;\\n\\t\\tmargin-bottom: 1rem;\\n\\t\\tbackground: var(--color-bg-1);\\n\\t\\tborder-radius: 8px;\\n\\t}\\n\\n\\t.date {\\n\\t\\ttext-align: center;\\n\\t\\tmin-width: 80px;\\n\\t\\tmargin-right: 2rem;\\n\\t}\\n\\n\\t.day {\\n\\t\\tdisplay: block;\\n\\t\\tfont-size: 2rem;\\n\\t\\tfont-weight: bold;\\n\\t}\\n\\n\\t.month {\\n\\t\\tdisplay: block;\\n\\t\\tfont-size: 1rem;\\n\\t}\\n\\n\\t.details {\\n\\t\\tflex-grow: 1;\\n\\t}\\n\\n\\t.details h3 {\\n\\t\\tmargin: 0;\\n\\t}\\n\\n\\t.details p {\\n\\t\\tmargin: 0.5rem 0 0;\\n\\t\\topacity: 0.8;\\n\\t}\\n\\n\\t.ticket-button {\\n\\t\\tpadding: 0.5rem 1rem;\\n\\t\\tbackground-color: var(--color-theme-1);\\n\\t\\tcolor: white;\\n\\t\\tborder-radius: 4px;\\n\\t\\twhite-space: nowrap;\\n\\t}\\n\\n\\t.ticket-button:hover {\\n\\t\\tbackground-color: #1a7ba1;\\n\\t\\tcolor: white;\\n\\t}\\n\\n\\t@media (max-width: 600px) {\\n\\t\\t.tour-date {\\n\\t\\t\\tflex-direction: column;\\n\\t\\t\\ttext-align: center;\\n\\t\\t\\tgap: 1rem;\\n\\t\\t\\tpadding: 1rem;\\n\\t\\t}\\n\\n\\t\\t.date {\\n\\t\\t\\tmargin-right: 0;\\n\\t\\t}\\n\\n\\t\\t.ticket-button {\\n\\t\\t\\twidth: 100%;\\n\\t\\t\\ttext-align: center;\\n\\t\\t}\\n\\t}\\n</style>"],"names":[],"mappings":"AAuBC,uCAAY,CACX,SAAS,CAAE,KAAK,CAChB,MAAM,CAAE,IAAI,CAAC,IAAI,CACjB,OAAO,CAAE,CAAC,CAAC,IACZ,CAEA,sCAAW,CACV,OAAO,CAAE,IAAI,CACb,WAAW,CAAE,MAAM,CACnB,OAAO,CAAE,MAAM,CACf,aAAa,CAAE,IAAI,CACnB,UAAU,CAAE,IAAI,YAAY,CAAC,CAC7B,aAAa,CAAE,GAChB,CAmBA,oCAAS,CACR,SAAS,CAAE,CACZ,CAEA,sBAAQ,CAAC,gBAAG,CACX,MAAM,CAAE,CACT,CAoBA,MAAO,YAAY,KAAK,CAAE,CACzB,sCAAW,CACV,cAAc,CAAE,MAAM,CACtB,UAAU,CAAE,MAAM,CAClB,GAAG,CAAE,IAAI,CACT,OAAO,CAAE,IACV,CAUD"}'
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-ymo6w6_START -->${$$result.title = `<title>Tour - NIVED</title>`, ""}<meta name="description" content="Check out upcoming tour dates and get tickets"><!-- HEAD_svelte-ymo6w6_END -->`, ""} <div class="container" data-svelte-h="svelte-uo0ql2"><h1>Tour Dates</h1> <div class="tour-dates svelte-134hhe"><div class="tour-date svelte-134hhe"> <div class="details svelte-134hhe"><h3 class="svelte-134hhe">Coming Soon</h3></div> </div></div> </div>`;
});
export {
  Page as default
};
