import { c as create_ssr_component } from "../../../chunks/ssr.js";
const css = {
  code: ".albums.svelte-124k5k{display:grid;grid-template-columns:repeat(auto-fit, minmax(250px, 1fr));gap:2rem;margin:2rem 0}.album.svelte-124k5k{text-align:center;padding:1rem;background:var(--color-bg-1);border-radius:8px}.stream-button.svelte-124k5k{display:inline-block;padding:0.5rem 1rem;background-color:var(--color-theme-1);color:white;border-radius:4px;margin-top:1rem;text-decoration:none}.stream-button.svelte-124k5k:hover{background-color:#1a7ba1;color:white}@media(max-width: 768px){.albums.svelte-124k5k{grid-template-columns:1fr;padding:0 1rem}}",
  map: '{"version":3,"file":"+page.svelte","sources":["+page.svelte"],"sourcesContent":["<svelte:head>\\n\\t<title>Music - Nicky Saturn</title>\\n\\t<meta name=\\"description\\" content=\\"Listen to the latest music from Nicky Saturn\\" />\\n</svelte:head>\\n\\n<div class=\\"container\\">\\n\\t<h1>Music</h1>\\n\\t\\n\\t<div class=\\"albums\\">\\n\\t\\t<div class=\\"album\\">\\n\\t\\t\\t<!-- Spotify Embed -->\\n\\t\\t\\t<iframe style=\\"border-radius:12px\\" src=\\"https://open.spotify.com/embed/artist/4qqgNsnTVsVq4o386eRAja?utm_source=generator&theme=0\\" width=\\"100%\\" height=\\"450\\" frameborder=\\"0\\" allow=\\"autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture\\" loading=\\"lazy\\"></iframe>\\n\\t\\t\\t\\n\\t\\t\\t<a href=\\"https://spotify.com\\" target=\\"_blank\\" rel=\\"noopener noreferrer\\" class=\\"stream-button\\">\\n\\t\\t\\t\\tStream on Spotify\\n\\t\\t\\t</a>\\n\\t\\t</div>\\n\\t\\t<div class=\\"album\\">\\n\\t\\t\\t<!-- Apple Music Embed (Direct iframe) -->\\n\\t\\t\\t<iframe src=\\"https://embed.music.apple.com/us/artist/nicky-saturn/1573096259\\" width=\\"100%\\" height=\\"450\\" frameborder=\\"0\\" allow=\\"autoplay; encrypted-media\\" allowfullscreen=\\"\\" loading=\\"lazy\\"></iframe>\\n\\t\\t\\n\\t\\t\\t<a href=\\"https://music.apple.com/us/artist/nicky-saturn/1573096259\\" target=\\"_blank\\" rel=\\"noopener noreferrer\\" class=\\"stream-button\\">\\n\\t\\t\\t\\tStream on Apple Music\\n\\t\\t\\t</a>\\n\\t\\t</div>\\n\\t\\t\\n\\t</div>\\n</div>\\n\\n<style>\\n\\t.albums {\\n\\t\\tdisplay: grid;\\n\\t\\tgrid-template-columns: repeat(auto-fit, minmax(250px, 1fr));\\n\\t\\tgap: 2rem;\\n\\t\\tmargin: 2rem 0;\\n\\t}\\n\\n\\t.album {\\n\\t\\ttext-align: center;\\n\\t\\tpadding: 1rem;\\n\\t\\tbackground: var(--color-bg-1);\\n\\t\\tborder-radius: 8px;\\n\\t}\\n\\n\\t.stream-button {\\n\\t\\tdisplay: inline-block;\\n\\t\\tpadding: 0.5rem 1rem;\\n\\t\\tbackground-color: var(--color-theme-1);\\n\\t\\tcolor: white;\\n\\t\\tborder-radius: 4px;\\n\\t\\tmargin-top: 1rem;\\n\\t\\ttext-decoration: none;\\n\\t}\\n\\n\\t.stream-button:hover {\\n\\t\\tbackground-color: #1a7ba1;\\n\\t\\tcolor: white;\\n\\t}\\n\\n\\t@media (max-width: 768px) {\\n\\t\\t.albums {\\n\\t\\t\\tgrid-template-columns: 1fr;\\n\\t\\t\\tpadding: 0 1rem;\\n\\t\\t}\\n\\t}\\n</style>\\n"],"names":[],"mappings":"AA8BC,qBAAQ,CACP,OAAO,CAAE,IAAI,CACb,qBAAqB,CAAE,OAAO,QAAQ,CAAC,CAAC,OAAO,KAAK,CAAC,CAAC,GAAG,CAAC,CAAC,CAC3D,GAAG,CAAE,IAAI,CACT,MAAM,CAAE,IAAI,CAAC,CACd,CAEA,oBAAO,CACN,UAAU,CAAE,MAAM,CAClB,OAAO,CAAE,IAAI,CACb,UAAU,CAAE,IAAI,YAAY,CAAC,CAC7B,aAAa,CAAE,GAChB,CAEA,4BAAe,CACd,OAAO,CAAE,YAAY,CACrB,OAAO,CAAE,MAAM,CAAC,IAAI,CACpB,gBAAgB,CAAE,IAAI,eAAe,CAAC,CACtC,KAAK,CAAE,KAAK,CACZ,aAAa,CAAE,GAAG,CAClB,UAAU,CAAE,IAAI,CAChB,eAAe,CAAE,IAClB,CAEA,4BAAc,MAAO,CACpB,gBAAgB,CAAE,OAAO,CACzB,KAAK,CAAE,KACR,CAEA,MAAO,YAAY,KAAK,CAAE,CACzB,qBAAQ,CACP,qBAAqB,CAAE,GAAG,CAC1B,OAAO,CAAE,CAAC,CAAC,IACZ,CACD"}'
};
const Page = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  $$result.css.add(css);
  return `${$$result.head += `<!-- HEAD_svelte-96x3zq_START -->${$$result.title = `<title>Music - Nicky Saturn</title>`, ""}<meta name="description" content="Listen to the latest music from Nicky Saturn"><!-- HEAD_svelte-96x3zq_END -->`, ""} <div class="container" data-svelte-h="svelte-txbwjv"><h1>Music</h1> <div class="albums svelte-124k5k"><div class="album svelte-124k5k"> <iframe style="border-radius:12px" src="https://open.spotify.com/embed/artist/4qqgNsnTVsVq4o386eRAja?utm_source=generator&amp;theme=0" width="100%" height="450" frameborder="0" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe> <a href="https://spotify.com" target="_blank" rel="noopener noreferrer" class="stream-button svelte-124k5k">Stream on Spotify</a></div> <div class="album svelte-124k5k"> <iframe src="https://embed.music.apple.com/us/artist/nicky-saturn/1573096259" width="100%" height="450" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen="" loading="lazy"></iframe> <a href="https://music.apple.com/us/artist/nicky-saturn/1573096259" target="_blank" rel="noopener noreferrer" class="stream-button svelte-124k5k">Stream on Apple Music</a></div></div> </div>`;
});
export {
  Page as default
};
